### ISSUE TITLE
Make sure the correct audience enums are used with the FB SDK

### ISSUE THREAD

**Issue by mathiaswking** [defold/extension-facebook#15]
On iOS we convert form our enum to a FB enum, but we don't on Android.
Is this really correct?

Also, can we skip our enums, and store the correct values in the Lua constants directly?
That way we won't need any conversions at all.

**Comment by britzl** [comment]
Obsolete. We do convert from Lua enums in `facebook_private.h` to Android enums `com.facebook.login.DefaultAudience.*` in function `DefaultAudience convertDefaultAudience(int fromLuaInt)` in `FacebookActivity.java`.
