### ISSUE TITLE
Defold 1.2.178 dynCall error

### ISSUE THREAD

**Issue by GreenArrow18** [defold/extension-facebook#27]
Getting an error on html5 builds when using the fb api (e.g. login window is opened):
Uncaught ReferenceError: dynCall is not defined

Most likely related to this:
https://github.com/AGulev/jstodef/issues/4

**Comment by JCash** [comment]
I'm not really sure how our tests didn't catch this?
We do build using the alpha version of bob, towards the stage server.

https://github.com/defold/test-sdk/runs/1612736459?check_suite_focus=true

**Comment by JCash** [comment]
Ah, is this a runtime error? @GreenArrow18

**Comment by AGulev** [comment]
yes, this is runtime error.

**Comment by JCash** [comment]
I'm currently unable to test properly myself at this moment, but here's a branch with a potential fix, if anyone feels like testing:
https://github.com/defold/extension-facebook/tree/emscripten-2-fix

**Comment by JCash** [comment]
Fixed in https://github.com/defold/extension-facebook/pull/28

**Comment by JCash** [comment]
Added new release
https://github.com/defold/extension-facebook/releases/tag/5.0.0
