### ISSUE TITLE
Update facebook sdk to support apple privacy manifest

### ISSUE THREAD

**Issue by vradyna-ms** [defold/extension-facebook#57]
Update facebook sdk to v17.0.0 when it will released to support apple privacy manifest
Brunch with privacy manifest: https://github.com/facebook/facebook-ios-sdk/compare/main...releases/v17.0.0
Issue: https://github.com/facebook/facebook-ios-sdk/issues/2264

**Comment by vradyna-ms** [comment]
New version is available https://github.com/facebook/facebook-ios-sdk/releases/tag/v17.0.0

**Comment by AGulev** [comment]
Facebook 17.0.0 has an issue in it https://github.com/facebook/facebook-ios-sdk/issues/2365
