### ISSUE TITLE
SSDP logs spam

### ISSUE THREAD

**Issue by msergienko-ms** [defold/extension-facebook#61]
![image](https://github.com/defold/extension-facebook/assets/94847833/dabfb4be-6f14-4a19-867f-05a154cee6aa)

**Comment by msergienko-ms** [comment]
Getiing heavily spammed bu SSDP logs like on the picture
Using filters helps, but being able to disable it completely would be nicer

**Comment by britzl** [comment]
Also reported here: https://github.com/defold/defold/issues/8828
